Added profile image to resolve issue #99
CatsInTech/Rezume pull request #120
Opened 2022-03-26 17:14 UTC by sebinfrancis7

## Added an option to let users add profile picture if needed

Closes: #99 

## Proposed changes

An option is provided for the users to add a profile picture of their choice to the resume.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

https://user-images.githubusercontent.com/59263190/160250189-37bd4a7d-c14b-4262-934b-3baf97568959.mp4

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2022-03-27 18:41 UTC, praveenscience requested changes
Really a good one. But please run prettier with the right config.

2022-03-27 18:41 UTC, praveenscience commented on src/components/Forms/Forms.js
> +            }
Run prettier on these.

2022-03-27 18:41 UTC, praveenscience commented on src/components/Forms/_FormElement.js
> +              </div>
Great one. Please run the prettier with the right config.

2022-03-27 18:41 UTC, praveenscience commented on src/components/Main/Main.js
> +            ImageHandler = {ImageHandler}
No spaces around `=`.

2022-03-27 18:41 UTC, praveenscience commented on src/components/Rezume/Rezume.js
> +      <p className="summary" style={{marginTop: ProfilePicture.Set ? "6rem":"2rem"}}>
No inline styles please.

2022-03-27 18:41 UTC, praveenscience commented on src/styles/_rezume.scss
> +  }
Run prettier on this.

2022-03-27 20:20 UTC, sebinfrancis7 commented
> Really a good one. But please run prettier with the right config.

Do I need to make any config changes while running the Prettier extension for Vscode ?

2022-03-27 20:21 UTC, sebinfrancis7 commented
> Really a good one. But please run prettier with the right config.

Do I need to make any config changes while running the Prettier extension for Vscode ? @praveenscience

2022-03-28 08:36 UTC, sebinfrancis7 commented
> Really a good one. But please run prettier with the right config.

Do I need to make any config changes while running the Prettier extension for Vscode ? Because when I tried to use prettier, it changes the formatting of the repo code as well. @praveenscience

2022-03-28 09:29 UTC, praveenscience commented
@sebinfrancis7 check the VS Code section of [My Personal Development Environment](https://blog.praveen.science/my-personal-development-environment/) and maybe this might help you: [My Visual Studio Code Settings · GitHub](https://gist.github.com/praveenscience/ebb5439f31774ad2fdc14cb9e7de1fc0).

2022-03-28 11:18 UTC, sebinfrancis7 commented
@praveenscience I have made the requested changes. Can you please review and merge.

2022-03-28 14:38 UTC, praveenscience commented
Lemme check now.

2022-03-28 14:39 UTC, praveenscience requested changes

2022-03-28 14:39 UTC, praveenscience commented on src/components/App.js
>        },
Run these through prettier please.

2022-03-28 14:39 UTC, praveenscience commented on src/components/Rezume/Rezume.js
>          <strong className="position">{CurrentPosition}</strong>
Run thee through prettier please.

2022-03-29 09:15 UTC, praveenscience requested changes
How are you running the prettier on? Just run on these files alone. Should work automatically. Do you need any help?

2022-03-29 09:15 UTC, praveenscience commented on src/components/Rezume/Rezume.js
> +  const { Name, Location, CurrentPosition, Summary,ProfilePicture } = Resume.About;
Not done.

2022-03-29 09:15 UTC, praveenscience commented on src/components/Rezume/Rezume.js
> +			</p>
Prettier?

2022-03-29 09:26 UTC, praveenscience commented on src/components/Rezume/Rezume.js
> +			</p>
Great - I guess you just need to do one thing. Change Tabs to 2 spaces. 😊

2022-03-29 09:27 UTC, praveenscience commented on src/components/Rezume/Rezume.js
> +  const { Name, Location, CurrentPosition, Summary,ProfilePicture } = Resume.About;
@sebinfrancis7 I really want this to be merged today. This is such a nice one. I am giving you the max points for this! <3

2022-03-29 09:27 UTC, sebinfrancis7 commented
I am doing the prettier changes manually, because while running on the whole file it changes the formatting of the code which was not written by me, which leads to the while file in git difference

2022-03-29 09:33 UTC, praveenscience commented on src/components/Rezume/Rezume.js
> +			</p>
@sebinfrancis7 This seems fine. Just run through prettier, even if the other lines aren't your code, gets changed, it's alright, we'll tweak it later. 😊

2022-03-29 09:37 UTC, sebinfrancis7 commented
Shall I push the formatting fixes? @praveenscience

2022-03-29 09:42 UTC, sebinfrancis7 commented
Can you check? @praveenscience 
Sorry to put you through the trouble 😅.

2022-03-29 10:04 UTC, praveenscience approved these changes
👍

2022-03-29 10:11 UTC, merged