Readme upadated
CatsInTech/Rezume pull request #146
Opened 2022-04-09 03:32 UTC by chetnaakhandagale

Please check the changes I made. This is my first time in open source contribution. Suggest anything if needed.

## Issue that this pull request solves

Closes: #140 

## Proposed changes

I have made very few changes in the readme. 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ x] Other (please describe): Only few punctuations were changed and some grammatical mistakes are corrected.

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in the user interface

## Other information

Any other information that is important to this pull request

2022-04-09 03:38 UTC, code-reaper08 requested changes
I've left a review 👍

2022-04-09 03:38 UTC, code-reaper08 commented on ReadME.md
> +Feel free to contact me at [catsintech@praveen.science](mail to:catsintech@praveen.science).
Hello @chetnaakhandagale 👋 
This should be retained as original to work as expected!

2022-04-09 03:38 UTC, code-reaper08 commented on ReadME.md
> +> This project is accepting contributions under [GirlScript Summer of Code 2022](https://gssoc.girlscript.tech/) - three monthly long Open Source program conducted by [GirlScript Foundation](https://
Guess it's **three-month** :-)

2022-04-10 08:18 UTC, praveenscience requested changes
I am not sure this one's a valid one... But happy to provide some value. Kindly refrain from these kind of PRs before asking.

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +Rezume is a free online portal for generating resumes without worrying about styling and formatting. In the web portal, you only need to input the basic information which you want to have on your res
Not needed change.

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +- [ ] [Linux Based Terminal](https://gitforwindows.org/) if you're using Windows and installed with Git.
Need a comma - basic grammar.

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +- [ ] **[Visual Studio Code](https://code.visualstudio.com/)** is the go-to editor for some complex languages like React using JSX or TypeScript and I finally agreed with [Wes Bos](https://wesbos.com
Both mean the same.

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +[Create React App](https://github.com/facebookincubator/create-react-app) is a comfortable environment for **learning React**, and is the best way to start building **a new [single-page](https://reac
We're not in Amreekah. We're either in India or the United Kingdom.

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +3. Open http://localhost:3000/ on your favourite browser. Let anyone from the mentoring team know if you are facing any troubles.
I'd go 75% with the comma here.

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +> This project is accepting contributions under [GirlScript Summer of Code 2022](https://gssoc.girlscript.tech/) - three-month long Open Source program conducted by [GirlScript Foundation](https://gs
Okay, this makes sense. 😊

2022-04-10 08:18 UTC, praveenscience commented on ReadME.md
> +*All communication will happen on the Slack channel for this particular project. Mentors can also be reached through GitHub. Avoid DMs and unnecessary mentions on slack and GitHub. *Check out [this](
These are okay, maybe the last line could replace: `[this](...) issue` with `[these issues](...)`.

2022-04-10 11:00 UTC, closed without merging