Changing Occupation Position and making copyright year dynamic Fixes …
CatsInTech/Rezume pull request #84
Opened 2022-03-02 17:28 UTC by Harshil-Jani

## Issue that this pull request solves

Closes: #81 
Closes: #82 

## Proposed changes
This PR consists of two changes
- The first change is changing the position of current Occupation of Person and separating it from the paragraph about them. Refer Issue #81 
- The second change is related to the footer of the website. In footer currently the year is hardcoded as 2020 in copyrights. But, This PR will change the hard coded string to Dynamic Year which will be changed automatically as year will change in future. Refer Issue #82 

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

![image](https://user-images.githubusercontent.com/79367883/156415427-afc1fb06-12ea-465b-b629-15f90f5f9e4c.png)

## Other information

Any other information that is important to this pull request

2022-03-02 18:25 UTC, praveenscience commented
I'll check this right away tomorrow. Thanks for contributing. As a thumb rule, please start working only after assignment of issue so that your efforts will not go in vain....

2022-03-02 18:56 UTC, Harshil-Jani commented
> As a thumb rule, please start working only after assignment of issue so that your efforts will not go in vain....

Opps, apologies. I will take care from now on.

2022-03-03 09:25 UTC, praveenscience commented
Running the deployments to see what's happening.

2022-03-03 19:45 UTC, Harshil-Jani commented
@praveenscience I have made new commits to the PR which consists of removing the UI changes which were not supposed to be changed as discussed in #81  And also, I have edited the ScreenShot in the PR description. So, Now this PR consists solving only the problem of making the Copyright Year Dynamic.

2022-03-04 10:56 UTC, Gurdeep475 commented
@Harshil-Jani I am not able to run the project in my local machine due to node-sass incompatibility error, how were able to solve that? Please help me.

2022-03-04 15:06 UTC, Harshil-Jani commented
@Gurdeep475  Downgrade your Node Sass to Lower version.
Being more specific go to your clone and run  `npm i node-sass@4.11.0`

2022-03-04 15:13 UTC, praveenscience approved these changes
👍

2022-03-04 15:13 UTC, praveenscience commented on src/styles/_rezume.scss
> +        font-weight: 550;
There's nothing called `550` for this.

2022-03-09 14:50 UTC, praveenscience requested changes

2022-03-09 14:50 UTC, praveenscience commented on src/components/Footer/Footer.js
> +
Why do we have unnecessary new lines?

2022-03-09 14:51 UTC, praveenscience approved these changes
I am just wondering, why didn't we do this without the intermediate variable? 👍

2022-03-09 14:52 UTC, merged